/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author DAVID
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palabras_guion = new javax.swing.JLabel();
        palabras_imagen2 = new javax.swing.JLabel();
        palabras_imagen3 = new javax.swing.JLabel();
        palabras_imagen4 = new javax.swing.JLabel();
        palabras_imagen5 = new javax.swing.JLabel();
        palabras_imagen6 = new javax.swing.JLabel();
        palabras_imagen7 = new javax.swing.JLabel();
        palabras_imagen8 = new javax.swing.JLabel();
        palabras_imagen9 = new javax.swing.JLabel();
        palabras_imagen10 = new javax.swing.JLabel();
        palabras_imagen11 = new javax.swing.JLabel();
        palabras_imagen12 = new javax.swing.JLabel();
        palabras_imagen13 = new javax.swing.JLabel();
        palabras_imagen14 = new javax.swing.JLabel();
        palabras_imagen15 = new javax.swing.JLabel();
        palabras_imagen16 = new javax.swing.JLabel();
        palabras_imagen17 = new javax.swing.JLabel();
        palabras_imagen18 = new javax.swing.JLabel();
        palabras_imagen19 = new javax.swing.JLabel();
        palabras_imagen20 = new javax.swing.JLabel();
        palabras_imagen21 = new javax.swing.JLabel();
        palabras_imagen22 = new javax.swing.JLabel();
        palabras_imagen23 = new javax.swing.JLabel();
        palabras_imagen24 = new javax.swing.JLabel();
        palabras_imagen25 = new javax.swing.JLabel();
        palabras_imagen26 = new javax.swing.JLabel();
        palabras_imagen27 = new javax.swing.JLabel();
        palabras_imagen28 = new javax.swing.JLabel();
        palabras_imagen29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        palabras_guion.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        palabras_guion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_guion.setText("_ _ _ _ _");
        palabras_guion.setName("guiones_palabras"); // NOI18N

        palabras_imagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen2.setText("A");

        palabras_imagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen3.setText("B");

        palabras_imagen4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen4.setText("E");

        palabras_imagen5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen5.setText("D");

        palabras_imagen6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen6.setText("C");

        palabras_imagen7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen7.setText("G");

        palabras_imagen8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen8.setText("F");

        palabras_imagen9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen9.setText("N");

        palabras_imagen10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen10.setText("M");

        palabras_imagen11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen11.setText("H");

        palabras_imagen12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen12.setText("I");

        palabras_imagen13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen13.setText("L");

        palabras_imagen14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen14.setText("K");

        palabras_imagen15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen15.setText("J");

        palabras_imagen16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen16.setText("T");

        palabras_imagen17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen17.setText("S");

        palabras_imagen18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen18.setText("Ñ");

        palabras_imagen19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen19.setText("O");

        palabras_imagen20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen20.setText("R");

        palabras_imagen21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen21.setText("Q");

        palabras_imagen22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen22.setText("P");

        palabras_imagen23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        palabras_imagen24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen24.setText("Z");

        palabras_imagen25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen25.setText("U");

        palabras_imagen26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen26.setText("V");

        palabras_imagen27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen27.setText("Y");

        palabras_imagen28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen28.setText("X");

        palabras_imagen29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palabras_imagen29.setText("W");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(palabras_guion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(palabras_imagen18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(palabras_imagen19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(palabras_imagen22, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(palabras_imagen21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(palabras_imagen20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palabras_imagen17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palabras_imagen16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(palabras_imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(palabras_imagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palabras_imagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(palabras_imagen11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(palabras_imagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palabras_imagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(palabras_imagen25, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen26, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen29, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen28, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(palabras_imagen27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(palabras_imagen24, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palabras_imagen23, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(palabras_guion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabras_imagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabras_imagen13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabras_imagen20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen22, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palabras_imagen27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen26, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen25, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen29, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen28, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen24, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabras_imagen23, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel palabras_guion;
    private javax.swing.JLabel palabras_imagen10;
    private javax.swing.JLabel palabras_imagen11;
    private javax.swing.JLabel palabras_imagen12;
    private javax.swing.JLabel palabras_imagen13;
    private javax.swing.JLabel palabras_imagen14;
    private javax.swing.JLabel palabras_imagen15;
    private javax.swing.JLabel palabras_imagen16;
    private javax.swing.JLabel palabras_imagen17;
    private javax.swing.JLabel palabras_imagen18;
    private javax.swing.JLabel palabras_imagen19;
    private javax.swing.JLabel palabras_imagen2;
    private javax.swing.JLabel palabras_imagen20;
    private javax.swing.JLabel palabras_imagen21;
    private javax.swing.JLabel palabras_imagen22;
    private javax.swing.JLabel palabras_imagen23;
    private javax.swing.JLabel palabras_imagen24;
    private javax.swing.JLabel palabras_imagen25;
    private javax.swing.JLabel palabras_imagen26;
    private javax.swing.JLabel palabras_imagen27;
    private javax.swing.JLabel palabras_imagen28;
    private javax.swing.JLabel palabras_imagen29;
    private javax.swing.JLabel palabras_imagen3;
    private javax.swing.JLabel palabras_imagen4;
    private javax.swing.JLabel palabras_imagen5;
    private javax.swing.JLabel palabras_imagen6;
    private javax.swing.JLabel palabras_imagen7;
    private javax.swing.JLabel palabras_imagen8;
    private javax.swing.JLabel palabras_imagen9;
    // End of variables declaration//GEN-END:variables
}
